{% set name = "daphne" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcbcace38eb86624ae247c7ffdc8ac12f155d7d19eafac4247381896d6f33761

build:
  number: 1
  entry_points:
    - daphne = daphne.cli:CommandLineInterface.entrypoint
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
    - pytest-runner
  run:
    - asgiref >=3.5.2,<4
    - autobahn >=22.4.2
    - python >={{ python_min }}
    - twisted >=22.4
    # twisted[tls] extra dependencies
    - pyopenssl >=16
    - service_identity >=18.1
    - idna >=2.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - daphne
    - twisted.plugins
  commands:
    - daphne --help

about:
  home: https://github.com/django/daphne
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Django ASGI (HTTP/WebSocket) server
  dev_url: https://github.com/django/daphne

extra:
  recipe-maintainers:
    - chrisbarber
    - swainn
