{% set name = "daphne" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cce9afc8f49a4f15d4270b8cfb0e0fe811b770a5cc795474e97e4da287497666

build:
  number: 1
  entry_points:
    - daphne = daphne.cli:CommandLineInterface.entrypoint
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - pytest-runner
  run:
    - asgiref >=3.5.2,<4
    - autobahn >=22.4.2
    - python >=3.7
    - twisted >=22.4
    # twisted[tls] extra dependencies
    - pyopenssl >=16
    - service_identity >=18.1
    - idna >=2.4

test:
  imports:
    - daphne
    - twisted.plugins
  commands:
    - daphne --help

about:
  home: https://github.com/django/daphne
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Django ASGI (HTTP/WebSocket) server
  dev_url: https://github.com/django/daphne

extra:
  recipe-maintainers:
    - chrisbarber
    - swainn
